{
  "name": "Slate Report - Sponsors",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Trials",
        "lineageTag": "5b0243b2-1acd-4071-b538-61cc1aa753a3",
        "columns": [
          {
            "name": "trial_id",
            "dataType": "string",
            "sourceColumn": "trial_id",
            "lineageTag": "dda3dc54-a404-4d0a-85e9-35a03d07977b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "lineageTag": "75065121-9445-4a3a-b4f8-ea7da9e55f4c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enrollment_status",
            "dataType": "string",
            "sourceColumn": "enrollment_status",
            "lineageTag": "913b34ed-17f3-4d7e-b94c-b9e6560a8455",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "phase",
            "dataType": "string",
            "sourceColumn": "phase",
            "lineageTag": "148823ff-e52d-40f6-8a03-d92fd9bfa63f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "best_guess_start_date",
            "dataType": "dateTime",
            "sourceColumn": "best_guess_start_date",
            "formatString": "Long Date",
            "lineageTag": "e56910b0-5b4c-4847-b27f-cc8da4076db5",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "31df49d2-5850-47d2-acb9-aeaa2f33952a",
                "defaultHierarchy": {
                  "table": "LocalDateTable_fda4d16d-986e-4fcd-89bf-bbf416ccb8d3",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "sponsors",
            "dataType": "string",
            "sourceColumn": "sponsors",
            "lineageTag": "33a1c6e2-7aa6-48e7-873f-5b050197c6cf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lead_sponsor_type",
            "dataType": "string",
            "sourceColumn": "lead_sponsor_type",
            "lineageTag": "8ea5bc74-c130-45ec-8ed7-c38b8a9cf0b4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "indications",
            "dataType": "string",
            "sourceColumn": "indications",
            "lineageTag": "4f69b66b-d54a-4691-bc55-f6f2858d61b8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lead_canonical_sponsor",
            "dataType": "string",
            "sourceColumn": "lead_canonical_sponsor",
            "lineageTag": "10f8ae0e-2d14-45d2-bdf9-447dba4bd323",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "is_industry",
            "dataType": "boolean",
            "sourceColumn": "is_industry",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8a902109-ec14-4b94-8aab-4a4734311e0a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "best_guess_end_date",
            "dataType": "dateTime",
            "sourceColumn": "best_guess_end_date",
            "formatString": "Long Date",
            "lineageTag": "c1e301da-09a5-4b2f-a182-72ae582fba49",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "e7d4a476-8614-4467-ba00-a22b679d877d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_3d058c96-1dd9-42b9-a781-b6666fca6b7b",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "lead_sponsor",
            "dataType": "string",
            "sourceColumn": "lead_sponsor",
            "lineageTag": "2345ea20-4f02-4863-9c93-8745b20d0af5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Final Lead Sponsors",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF(Trials[lead_canonical_sponsor]=BLANK(),Trials[lead_sponsor],Trials[lead_canonical_sponsor])",
            "lineageTag": "01fcdee4-4f58-4e2c-8bb0-74df154fe581",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "BestGuessStart_Year Flag",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF(OR(AND(Trials[best_guess_start_date]<=TODAY(),DATEDIFF(Trials[best_guess_start_date],TODAY(),YEAR)<=20),AND(Trials[best_guess_start_date]>TODAY(),DATEDIFF(TODAY(),'Trials'[best_guess_start_date],YEAR)<=5)),\"Yes\",\"No\")",
            "lineageTag": "5b733403-68f9-42be-92fb-45aa2a02c32e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "BestGuessEnd_Year Flag",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF(OR(AND(Trials[best_guess_end_date]<=TODAY(),DATEDIFF(Trials[best_guess_end_date],TODAY(),YEAR)<=20),AND(Trials[best_guess_end_date]>TODAY(),DATEDIFF(TODAY(),'Trials'[best_guess_end_date],YEAR)<=5)),\"Yes\",\"No\")",
            "lineageTag": "b5dafaad-edcb-4040-a6c9-c17c00410478",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Trials-a90a0433-9792-4e43-9f3d-4ce1c9d9a85b",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-222002196911544.4.azuredatabricks.net\", \"/sql/1.0/warehouses/5976f83cc666e24e\", [Catalog = \"\", Database = \"\"]),",
                "    core_ontology_v1_Database = Source{[Name=\"core_ontology_v1\",Kind=\"Database\"]}[Data],",
                "    hubble_Schema = core_ontology_v1_Database{[Name=\"hubble\",Kind=\"Schema\"]}[Data],",
                "    trials_Table = hubble_Schema{[Name=\"trials\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(trials_Table,{\"trial_id\", \"status\", \"enrollment_status\", \"phase\", \"best_guess_start_date\", \"sponsors\", \"lead_sponsor\", \"lead_sponsor_type\", \"indications\", \"is_industry\", \"best_guess_end_date\", \"lead_canonical_sponsor\"}),",
                "    #\"Split Column by Delimiter\" = Table.ExpandListColumn(Table.TransformColumns(#\"Removed Other Columns\", {{\"sponsors\", Splitter.SplitTextByDelimiter(\",\", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), \"sponsors\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"sponsors\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"[\",\"\",Replacer.ReplaceText,{\"sponsors\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"]\",\"\",Replacer.ReplaceText,{\"sponsors\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value1\", each not Text.StartsWith([sponsors], \"(Other\")),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each ([status] <> \"Terminated\")),",
                "    #\"Split Column by Delimiter1\" = Table.ExpandListColumn(Table.TransformColumns(#\"Filtered Rows1\", {{\"indications\", Splitter.SplitTextByDelimiter(\",\", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), \"indications\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"indications\", type text}}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Changed Type1\",\"[\",\"\",Replacer.ReplaceText,{\"indications\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"]\",\"\",Replacer.ReplaceText,{\"indications\"})",
                "in",
                "    #\"Replaced Value3\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "SponsorRank",
            "expression": "RANKX(ALLSELECTED(Trials[Final Lead Sponsors]),COUNT(Trials[trial_id]),,DESC,Skip)",
            "formatString": "0",
            "lineageTag": "339bed1f-7f97-4800-b0cc-8aeb090bb2f3"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "DateTableTemplate_7021b6f6-0212-4490-baed-9425c653df0e",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "102b8f8b-b532-45d1-9511-1bae43bf9ea7",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "6f530ac2-b286-478e-9ae5-21cdfa25aa18",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "47e02f06-8854-4641-8c94-916791a94fb3",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "4fd2ac3f-fae4-4aaf-88c8-60b1b575292b",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "c1640acf-62ae-4ff9-8d60-25e8541b8891",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "4fe41966-a94c-4935-b269-4e0951c2f66b",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "e5f74238-76f1-45d8-beec-3aacd1ae1423",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "69b0394a-f57c-4dcd-8820-14de4bf35748",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_7021b6f6-0212-4490-baed-9425c653df0e-0d9f8f19-7584-4557-8bd0-a25a20360e69",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "91652249-1f50-4292-bf6f-3fb736dfe310",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "1f507c2c-ff17-47ae-8375-7736f09cabda"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "8d0d605e-9baf-4a3d-a73b-6ded15837035"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "9197fc67-78d9-4ab1-954c-731b73ae3b39"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "da989a41-8e07-4aa0-bc75-894fe9886c4c"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_fda4d16d-986e-4fcd-89bf-bbf416ccb8d3",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "3f97c9e3-b75c-460a-911e-a9d1e606c66c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "8c64596f-cf71-41fe-8be0-f50e49bc0729",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "d43cbe5b-7f4e-4521-b378-5cb7c6ffca6e",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "8b623567-b596-45d9-9ab2-2e8cc956316b",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "8ac09b31-877b-4044-aa09-ec29a751db4e",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "69c5bf84-9de1-4b90-8cc4-2d06630e4da4",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "acecd5ce-82ad-4ba5-b624-6fcd684c071d",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "2a22f463-65ae-4dc6-8de4-b27adbedcbd6",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_fda4d16d-986e-4fcd-89bf-bbf416ccb8d3-e0fea4a5-e904-442b-a3e0-0e3c97a72985",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Trials'[best_guess_start_date])), 1, 1), Date(Year(MAX('Trials'[best_guess_start_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "779989d4-9734-45a0-a769-1818b4667c56",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "5caaac3e-d8f4-4726-a45f-2d210e2138cd"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "432bfa57-6d6f-4362-a8d9-a339f277e890"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "6bdb4ba9-0d61-4c71-934d-98f8d5c88e90"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "6839c2a7-c407-4849-b604-fb6e110633e6"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Sponsors",
        "lineageTag": "b7a07b33-b3da-47ff-874b-b85401efc279",
        "columns": [
          {
            "name": "sponsors",
            "dataType": "string",
            "sourceColumn": "sponsors",
            "lineageTag": "c442222a-939f-472b-8033-6a8a634bd463",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sponsor_canonical_name",
            "dataType": "string",
            "sourceColumn": "sponsor_canonical_name",
            "lineageTag": "173621b0-2c9a-4f13-a87a-05c180b8bbd3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sponsor_type",
            "dataType": "string",
            "sourceColumn": "sponsor_type",
            "lineageTag": "99784572-4e16-4ce0-b1ce-3c079228e6f8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sponsors-949a8e6b-5b44-4b09-b542-24449c2325a4",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-222002196911544.4.azuredatabricks.net\", \"/sql/1.0/warehouses/5976f83cc666e24e\", [Catalog = \"\", Database = \"\"]),",
                "    core_ontology_v1_Database = Source{[Name=\"core_ontology_v1\",Kind=\"Database\"]}[Data],",
                "    hubble_Schema = core_ontology_v1_Database{[Name=\"hubble\",Kind=\"Schema\"]}[Data],",
                "    sponsors_Table = hubble_Schema{[Name=\"sponsors\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(sponsors_Table,{\"sponsor_specific_name\", \"sponsor_canonical_name\", \"sponsor_type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"sponsor_specific_name\", \"sponsors\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Exclude Trials",
        "lineageTag": "833657b0-cf2a-49fa-9532-9de87a63d3c9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "trial_id",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Trials[trial_id]",
            "lineageTag": "09531264-4f60-4ef1-9552-73cfd923cd84",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Exclude Trials-4c4952ba-896c-4b8e-b11b-2b434b1da668",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DISTINCT(Trials[trial_id])"
            }
          }
        ],
        "measures": [
          {
            "name": "Exclude Trials",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Exclude Trials'[trial_id] ),",
              "    COUNTROWS (",
              "        EXCEPT (VALUES ( Trials[trial_id] ), VALUES ('Exclude Trials'[trial_id] ))",
              "    ),",
              "    1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "46627630-0668-4cb3-984a-c5dfda47c06e"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3690c27cb35046fa87acbc014668f40a"
          }
        ]
      },
      {
        "name": "LocalDateTable_3d058c96-1dd9-42b9-a781-b6666fca6b7b",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "34a48f22-a2c2-408c-b20a-17f0b2efce5b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "2910ea32-23c5-469f-a21d-e863d015d9d2",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "cd51842c-443b-4a5b-ab44-308e105db79e",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "77fae79a-d758-4824-b2d4-adf6cc53404d",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "194d631a-e84e-45a3-ba26-6c2566e0d48f",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "0a3b91ab-e56b-4f05-8a03-8b98962d6df4",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "c7d6df08-6501-4573-b44b-e450dc57287b",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "12eee530-d2b4-41eb-bc6d-26cffc6a2c30",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_3d058c96-1dd9-42b9-a781-b6666fca6b7b-a1e40139-d49d-4288-8635-9c300d27bf76",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Trials'[best_guess_end_date])), 1, 1), Date(Year(MAX('Trials'[best_guess_end_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "85f19795-e60e-49ad-8f80-15cdd9c0e293",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "b4ffe0fa-4a9c-4ee9-843e-6449ec8cda3a"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "10efe666-e9e2-4989-a8b7-09009f4f480e"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "3e5b7c3e-1ffa-474c-916b-6dbe8dadc793"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "6ac09b2e-a6ab-4cc9-87e7-c7ce8ab9dd69"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "31df49d2-5850-47d2-acb9-aeaa2f33952a",
        "fromTable": "Trials",
        "fromColumn": "best_guess_start_date",
        "toTable": "LocalDateTable_fda4d16d-986e-4fcd-89bf-bbf416ccb8d3",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "f0eda72c-07a1-4c1a-8da4-8167ecdf476f",
        "toCardinality": "many",
        "fromTable": "Trials",
        "fromColumn": "sponsors",
        "toTable": "Sponsors",
        "toColumn": "sponsors"
      },
      {
        "name": "e7d4a476-8614-4467-ba00-a22b679d877d",
        "fromTable": "Trials",
        "fromColumn": "best_guess_end_date",
        "toTable": "LocalDateTable_3d058c96-1dd9-42b9-a781-b6666fca6b7b",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "expressions": [
      {
        "name": "sponsors_bridge",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Databricks.Catalogs(\"adb-222002196911544.4.azuredatabricks.net\", \"/sql/1.0/warehouses/5976f83cc666e24e\", [Catalog = \"\", Database = \"\"]),",
          "    core_ontology_Database = Source{[Name=\"core_ontology\",Kind=\"Database\"]}[Data],",
          "    hubble_Schema = core_ontology_Database{[Name=\"hubble\",Kind=\"Schema\"]}[Data],",
          "    sponsors_Table = hubble_Schema{[Name=\"sponsors\",Kind=\"Table\"]}[Data],",
          "    #\"Removed Other Columns\" = Table.SelectColumns(sponsors_Table,{\"sponsor_specific_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"sponsor_specific_name\", \"sponsors\"}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Renamed Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "lineageTag": "1b2eb5f5-e612-4670-9a64-dd6a1d271bd9",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Trials\",\"Sponsors\",\"sponsors_bridge\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.116.966.0 (23.04)"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}